<?php

/**
 * Plugin autostartpage: English language file
 *
 * @license    GPL 2 (http://www.gnu.org/licenses/gpl.html)
 * @author     Charles Knight <charles@rabidaudio.com>
 */

$lang['createmsg'] = 'Autogenerated start page for this namespace:';
$lang['failmsg'] = 'Autogeneration of start page for this namespace failed. You may not have permission to create this page.';
$lang['templatemissing'] = "Warning: Couldn't create start page, template file doesn't exist or could not be read.";