# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 15 May 2020 01:37:49 +0000
*               @ALL          0
*               @user         8
