<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 24 Apr 2020 01:11:31 +0200
 */

$conf['title'] = 'DokuRoam';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['recent'] = 0;
$conf['recent_days'] = 0;
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['phpok'] = 1;
$conf['plugin']['todo']['AllowLinks'] = 1;
$conf['plugin']['todo']['ActionNamespace'] = 'notes';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cosmo';
$conf['tpl']['bootstrap3']['sidebarPosition'] = 'right';
$conf['tpl']['bootstrap3']['leftSidebarGrid'] = 'col-sm-3 col-md-4';
$conf['tpl']['bootstrap3']['rightSidebarGrid'] = 'col-sm-3 col-md-4';
$conf['tpl']['bootstrap3']['showLandingPage'] = 1;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';

// end auto-generated content
